server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.81.128:3306/JPAtest?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    #type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: true #是否显示数据库语句
  redis:
    database: 0
    host: 127.0.0.1
    password: '123456'
    port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml

scheduler:
  # 定时任务的时间，每5秒执行一次
  testCron: 0/5 * * * * ?

logging:
  file:
    path: log


my-profile:
  name: 马富贵
  email: windxiao@vip.qq.com

library:
  location: 西安
  books:
    - name: 天才基本法
      description: 二十二岁的林朝夕在父亲确诊阿尔茨海默病这天，得知自己暗恋多年的校园男神裴之即将出国深造的消息——对方考取的学校，恰是父亲当年为她放弃的那所。
    - name: 时间的秩序
      description: 为什么我们记得过去，而非未来？时间“流逝”意味着什么？是我们存在于时间之内，还是时间存在于我们之中？卡洛·罗韦利用诗意的文字，邀请我们思考这一亘古难题——时间的本质。
    - name: 了不起的我
      description: 如何养成一个新习惯？如何让心智变得更成熟？如何拥有高质量的关系？ 如何走出人生的艰难时刻？


